#!/bin/python3
import sys
import argparse
import subprocess
import shutil

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', action='store_true')

args = parser.parse_args()

bin_src_path = 'target/riscv64gc-unknown-none-elf/release/hv-rv64-virt'
if args.debug:
    bin_src_path = 'target/riscv64gc-unknown-none-elf/debug/hv-rv64-virt'

bin_dst_path = 'target/hv-rv64-virt'
shutil.copy2(bin_src_path, bin_dst_path)

cmd = [
    'qemu-system-riscv64', '-nographic', '-M', 'virt', '-icount', 'shift=10',
    '-bios', bin_dst_path,
    '-device', 'virtio-serial-device',
    '-device', 'virtserialport,id=serial7',
    '-chardev', 'file,id=serial7,path=somedata.bin',
]

if args.debug:
    cmd.extend(['-s', '-S'])


print("starting sim: ", cmd)
subprocess.run(cmd)
